name: chat_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  intl: ^0.17.0
  firebase_auth: ^3.5.1
  cloud_firestore: ^3.4.1
  firebase_storage: ^10.3.3
  uuid: ^3.0.6
  flutter_gen_runner: ^4.3.0
  flutter_svg: ^1.1.1+1
  firebase_core: ^1.20.0
  json_to_model: ^3.1.8+beta
  quiver: ^3.1.0
  image_picker: ^0.8.5+3
  google_maps_flutter: ^2.1.10
  dio: ^4.0.6
  flutter_polyline_points: ^1.0.0
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_api_headers: ^1.3.0
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:


  uses-material-design: true

 
  assets:
    - assets/images/
    - assets/icons/

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
