// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgyUIo7Q8MpZ48BYPtsPavSTreSXTkg3E',
    appId: '1:401950548500:web:841340b1e9a3d472c97d01',
    messagingSenderId: '401950548500',
    projectId: 'chat-app-flutter-5218c',
    authDomain: 'chat-app-flutter-5218c.firebaseapp.com',
    storageBucket: 'chat-app-flutter-5218c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7mbmwOvC4BwTB76F_vW2Z2YH6ZocGls',
    appId: '1:401950548500:android:afd6df0f1507c5ccc97d01',
    messagingSenderId: '401950548500',
    projectId: 'chat-app-flutter-5218c',
    storageBucket: 'chat-app-flutter-5218c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1vYI6g3MfL2Ni3DMnLMtSnUkXYsjHBM',
    appId: '1:401950548500:ios:66fde876a8b425edc97d01',
    messagingSenderId: '401950548500',
    projectId: 'chat-app-flutter-5218c',
    storageBucket: 'chat-app-flutter-5218c.appspot.com',
    iosClientId: '401950548500-0mbrplh6f90bt92i26go3r1gqv61n46t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1vYI6g3MfL2Ni3DMnLMtSnUkXYsjHBM',
    appId: '1:401950548500:ios:66fde876a8b425edc97d01',
    messagingSenderId: '401950548500',
    projectId: 'chat-app-flutter-5218c',
    storageBucket: 'chat-app-flutter-5218c.appspot.com',
    iosClientId: '401950548500-0mbrplh6f90bt92i26go3r1gqv61n46t.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
